(function(){'use strict';
 const core=window.HLAdmissionsCore,data=window.HLAdmissionsData||[],doc=document;
 const subjects=[['Toán','toán'],['Vật lý','lý'],['Hóa học','hóa'],['Sinh học','sinh'],['Ngữ văn','văn'],['Tiếng Anh','anh']];
 function el(tag,cls,text){const x=doc.createElement(tag);if(cls)x.className=cls;if(text!=null)x.textContent=text;return x;}
 function icon(name){return window.HLIcons?.icon(name)||'';}
 function mount(){const host=doc.getElementById('hl-learning-body');if(!host||host.querySelector('.admissions-planner'))return;const wrap=el('section','st-panel admissions-planner');const intro=el('div','ad-intro');const svg=el('span');svg.innerHTML=icon('compass');intro.append(svg);const copy=el('div');copy.append(el('h2',null,'Xếp 15 nguyện vọng có chiến lược'),el('p','ad-meta','Nhập sở thích, tổ hợp môn và điểm thi. Hệ thống đối chiếu điểm chuẩn THPT 2025 trong bộ dữ liệu tham khảo rồi chia Mơ ước · Phù hợp · An toàn.'));intro.append(copy);wrap.append(intro);
  const form=el('form','ad-form');const likes=el('fieldset','ad-full');likes.append(el('legend',null,'Bạn quan tâm lĩnh vực nào?'));const checks=el('div','ad-checks');for(const v of ['Công nghệ','Kinh doanh','Truyền thông','Hóa học','Sinh học','Ngoại ngữ','Giáo dục','Kỹ thuật']){const l=el('label');const i=el('input');i.type='checkbox';i.name='interest';i.value=v;l.append(i,doc.createTextNode(v));checks.append(l);}likes.append(checks);form.append(likes);
  const sub=el('fieldset','ad-full');sub.append(el('legend',null,'Môn/tổ hợp bạn dự kiến dùng'));const sc=el('div','ad-checks');for(const [label,val]of subjects){const l=el('label');const i=el('input');i.type='checkbox';i.name='subject';i.value=val;l.append(i,doc.createTextNode(label));sc.append(l);}sub.append(sc);form.append(sub);
  const scores=el('div','ad-scores ad-full');for(const [name,label]of [['score','Tổng điểm 3 môn'],['bonus','Điểm ưu tiên'],['region','Khu vực'],['year','Năm dữ liệu']]){const l=el('label');l.append(doc.createTextNode(label));const i=el('input');i.name=name;i.type=name==='region'||name==='year'?'text':'number';i.step='0.01';i.min='0';i.max=name==='score'?'30':'3';i.value=name==='score'?'':name==='year'?'2025':'';if(name==='score')i.required=true;scores.append(l);l.append(i);}form.append(scores);
  const controls=el('div','ad-controls ad-full');const run=el('button','st-button st-primary');run.type='submit';run.innerHTML=icon('compass')+' Tạo danh sách nguyện vọng';const reset=el('button','st-button','Xóa kết quả');reset.type='button';controls.append(run,reset);form.append(controls);const message=el('div','ad-message','Dữ liệu điểm chuẩn là tham khảo, mỗi ngành có thể khác tổ hợp/phương thức. Hãy mở nguồn chính thức trước khi đăng ký.');form.append(message);wrap.append(form);const results=el('div','ad-results');wrap.append(results);host.append(wrap);
  function render(rows){results.replaceChildren();const groups={dream:'Mơ ước · cao hơn khoảng 1–2 điểm',match:'Phù hợp · sát năng lực',safe:'An toàn · thấp hơn năng lực'};const heading=el('div','ad-message',`Đã xếp ${rows.length} nguyện vọng theo thứ tự ưu tiên. ${groups.dream} / ${groups.match} / ${groups.safe}.`);results.append(heading);for(const r of rows){const row=el('article','ad-row');row.dataset.group=r.group;row.append(el('div','ad-number',String(r.position).padStart(2,'0')));const body=el('div');body.append(el('span','ad-badge',r.groupLabel));body.append(el('h3',null,r.major));body.append(el('p',null,r.school));body.append(el('p','ad-meta',`Điểm chuẩn tham khảo 2025: ${r.cutoff.toFixed(2)} · Tổ hợp: ${r.combinations.join(', ')} · Chênh lệch với bạn: ${r.gap>=0?'+':''}${r.gap.toFixed(2)}`));const a=el('a',null,'Xem nguồn điểm chuẩn ↗');a.href=r.source;a.target='_blank';a.rel='noopener noreferrer';body.append(a);row.append(body);const tools=el('div','ad-tools');const up=el('button',null,'↑');const down=el('button',null,'↓');up.disabled=r.position===1;down.disabled=r.position===rows.length;up.onclick=()=>move(r.position,-1);down.onclick=()=>move(r.position,1);tools.append(up,down);row.append(tools);results.append(row);}}
  let current=[];function move(pos,delta){const i=pos-1,j=i+delta;if(j<0||j>=current.length)return;[current[i],current[j]]=[current[j],current[i]];current=current.map((x,k)=>({...x,position:k+1}));render(current);}
  form.addEventListener('submit',e=>{e.preventDefault();const fd=new FormData(form),raw=Number(fd.get('score')),bonus=Number(fd.get('bonus')||0),score=raw+bonus;if(!Number.isFinite(raw)||raw<0||raw>30||!Number.isFinite(bonus)||bonus<0||bonus>3){message.textContent='Điểm thi phải nằm trong khoảng 0–30, điểm ưu tiên 0–3.';return;}const interests=fd.getAll('interest'),chosen=fd.getAll('subject');current=core.rank(data,{score,subjects:chosen,interests});render(current);try{HL.storage.set('htvvm.admissionsPlan.'+(window.auth?.currentUser?.uid||'guest'),{score,raw,bonus,subjects:chosen,interests,rows:current,createdAt:Date.now()});}catch{}message.textContent='Đã lưu bản kế hoạch trên thiết bị này. Hãy kiểm tra lại thông tin tuyển sinh chính thức.';});reset.onclick=()=>{form.reset();results.replaceChildren();message.textContent='Dữ liệu điểm chuẩn là tham khảo, mỗi ngành có thể khác tổ hợp/phương thức. Hãy mở nguồn chính thức trước khi đăng ký.';};
  const previous=HL.storage.get('htvvm.admissionsPlan.'+(window.auth?.currentUser?.uid||'guest'));if(previous?.rows?.length){current=previous.rows;render(current);}
 }
 const observer=new MutationObserver(()=>{if(doc.getElementById('hl-learning-body')&&!doc.querySelector('.admissions-planner'))mount();});observer.observe(doc.body,{subtree:true,childList:true});
 document.addEventListener('DOMContentLoaded',mount);
})();
