(function(){'use strict';
 const $=id=>document.getElementById(id);
 async function tokenApi(path,options={}){const user=window.auth?.currentUser;if(!user)throw Object.assign(new Error('AUTH'),{status:401});const jwt=await user.getIdToken();const r=await fetch(path,{...options,headers:{'Content-Type':'application/json',Authorization:'Bearer '+jwt},cache:'no-store'});let data={};try{data=await r.json()}catch{}if(!r.ok)throw Object.assign(new Error(data.error||'API error'),{status:r.status,data});return data;}
 function card(title){const x=document.createElement('article');x.className='hl-card p-6';const h=document.createElement('h2');h.className='font-black text-xl';h.textContent=title;x.append(h);return x;}
 function render(){const host=$('sec-admin-center');if(!host)return;host.innerHTML='';const heading=document.createElement('div');heading.className='mb-6';heading.innerHTML='<p class="text-xs font-black tracking-[.2em] text-violet-600 uppercase">ADMIN TOKEN CENTER</p><h1 class="text-3xl font-black mt-1">Quản trị token</h1><p class="text-sm text-slate-500 mt-2">Mọi thay đổi balance chạy qua backend, transaction và audit log.</p>';host.append(heading);
  const search=card('Tìm người dùng');const form=document.createElement('form');form.className='flex flex-col sm:flex-row gap-2';const input=document.createElement('input');input.id='admin-user-q';input.className='tw-input flex-1';input.placeholder='Email hoặc UID';input.required=true;const btn=document.createElement('button');btn.className='px-4 py-3 rounded-xl bg-violet-600 text-white font-black';btn.textContent='Tìm';form.append(input,btn);const results=document.createElement('div');results.id='admin-user-results';results.className='mt-4 space-y-2';search.append(form,results);host.append(search);
  const panel=document.createElement('div');panel.id='admin-wallet-panel';panel.className='grid grid-cols-1 xl:grid-cols-2 gap-5 mt-5 hidden';host.append(panel);
  form.addEventListener('submit',async e=>{e.preventDefault();results.textContent='Đang tìm…';try{const d=await tokenApi('/api/admin-users?q='+encodeURIComponent(input.value));results.replaceChildren();if(!d.users?.length){results.textContent='Không tìm thấy người dùng.';return;}for(const u of d.users){const b=document.createElement('button');b.type='button';b.className='w-full text-left p-4 rounded-2xl border border-slate-200 hover:border-violet-300 hover:bg-violet-50';b.innerHTML=`<b>${escapeHtml(u.name)}</b><span class="block text-xs text-slate-500 mt-1">${escapeHtml(u.email)} · ${escapeHtml(u.uid)}</span>`;b.onclick=()=>loadUser(u.uid);results.append(b);}}catch(err){results.textContent=err.data?.error||'Không thể tìm người dùng.';}});
  function escapeHtml(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));}
  async function loadUser(uid){panel.classList.remove('hidden');panel.innerHTML='<div class="hl-card p-6 xl:col-span-2">Đang tải ví…</div>';try{const d=await tokenApi('/api/admin-token?uid='+encodeURIComponent(uid));const user=d.user,w=d.wallet;panel.innerHTML='';const info=card('Người dùng');info.innerHTML+=`<div class="grid sm:grid-cols-3 gap-3 mt-4"><div><span class="text-xs text-slate-500">Tên</span><b class="block">${escapeHtml(user.name)}</b></div><div><span class="text-xs text-slate-500">Email</span><b class="block break-all">${escapeHtml(user.email)}</b></div><div><span class="text-xs text-slate-500">UID</span><b class="block break-all">${escapeHtml(user.uid)}</b></div></div><div class="grid sm:grid-cols-3 gap-3 mt-5"><div class="p-4 rounded-2xl bg-emerald-50"><span class="text-xs text-slate-500">Token hiện tại</span><b class="block text-2xl">${w.balance.toLocaleString('vi-VN')}</b></div><div class="p-4 rounded-2xl bg-blue-50"><span class="text-xs text-slate-500">Tổng đã nhận</span><b class="block text-2xl">${w.lifetimeEarned.toLocaleString('vi-VN')}</b></div><div class="p-4 rounded-2xl bg-amber-50"><span class="text-xs text-slate-500">Tổng đã tiêu</span><b class="block text-2xl">${w.lifetimeSpent.toLocaleString('vi-VN')}</b></div></div>`;panel.append(info);
    for(const [type,title] of [['grant','+ Cộng token'],['deduct','− Trừ token']]){const c=card(title);const f=document.createElement('form');f.className='space-y-3';const a=document.createElement('input');a.type='number';a.min='1';a.max=type==='deduct'?'100000':'1000000';a.required=true;a.className='tw-input';a.placeholder='Số lượng';const r=document.createElement('input');r.required=true;r.maxLength=500;r.className='tw-input';r.placeholder='Lý do (bắt buộc)';const sub=document.createElement('button');sub.className='w-full py-3 rounded-xl '+(type==='grant'?'bg-emerald-600':'bg-rose-600')+' text-white font-black';sub.textContent=type==='grant'?'Xác nhận cộng':'Xác nhận trừ';f.append(a,r,sub);c.append(f);f.addEventListener('submit',async e=>{e.preventDefault();sub.disabled=true;try{const out=await tokenApi('/api/admin-token',{method:'POST',body:JSON.stringify({uid,amount:Number(a.value),reason:r.value,type})});window.toast?.(`Đã cập nhật ${out.wallet.balance.toLocaleString('vi-VN')} token.`);await loadUser(uid);}catch(err){window.toast?.(err.data?.error||'Không thể cập nhật token.');}finally{sub.disabled=false;}});panel.append(c);}
    const history=card('Lịch sử token');const table=document.createElement('div');table.className='overflow-x-auto mt-4';table.innerHTML='<table class="min-w-full text-sm"><thead><tr><th class="text-left p-2">Thời gian</th><th class="text-left p-2">Loại</th><th class="text-left p-2">Số token</th><th class="text-left p-2">Nguồn</th><th class="text-left p-2">Admin</th><th class="text-left p-2">Lý do</th><th class="text-left p-2">Transaction ID</th></tr></thead></table>';const tbody=document.createElement('tbody');for(const tx of d.ledger||[]){const tr=document.createElement('tr');const when=new Date(tx.createdAt||0).toLocaleString('vi-VN');tr.innerHTML=`<td class="p-2 whitespace-nowrap">${escapeHtml(when)}</td><td class="p-2">${escapeHtml(tx.type)}</td><td class="p-2">${escapeHtml(tx.amount)}</td><td class="p-2">${escapeHtml(tx.source)}</td><td class="p-2">${escapeHtml(tx.adminUid||'—')}</td><td class="p-2">${escapeHtml(tx.reason||'')}</td><td class="p-2 text-xs break-all">${escapeHtml(tx.transactionId)}</td>`;tbody.append(tr);}table.querySelector('table').append(tbody);history.append(table);panel.append(history);
   }catch(err){panel.innerHTML='<div class="hl-card p-6 text-rose-600 font-bold">'+escapeHtml(err.data?.error||'Không thể tải dữ liệu ví.')+'</div>';}}
 }
 window.HLAdmin={open(){if(!window.HLRequireRole?.('admin'))return;switchSection('sec-admin-center');render();},render};
 document.addEventListener('DOMContentLoaded',()=>{if(window.HLAuthz?.admin)render();});
 window.addEventListener('hl:admin-role-ready',()=>render());
})();
