(function(){'use strict';
 let data=null,active='study';const $=id=>document.getElementById(id);
 const labels={study:'Hôm nay · Thời gian học',streak:'Streak · Chuỗi ngày',exam:'Điểm thi · Điểm cao nhất trong lịch sử bài thi',token:'Token · Tổng số dư hiện tại'};
 function format(type,v){if(type==='study')return `${Math.floor(v/60)} phút`;if(type==='exam')return `${v}/10`;if(type==='token')return `${Number(v).toLocaleString('vi-VN')} token`;return `${v} ngày`;}
 async function load(){try{const u=window.auth?.currentUser;if(!u)return;const t=await u.getIdToken();const r=await fetch('/api/leaderboards',{headers:{Authorization:'Bearer '+t},cache:'no-store'});if(!r.ok)throw new Error('HTTP '+r.status);data=await r.json();render();}catch(e){const box=$('leaderboard-content');if(box)box.textContent='Chưa tải được bảng xếp hạng.';}}
 function render(){const box=$('leaderboard-content');if(!box||!data)return;box.replaceChildren();const rows=data[active]||[];const h=document.createElement('div');h.innerHTML=`<p class="text-xs font-black tracking-[.16em] text-slate-500 uppercase">${labels[active]}</p><h3 class="text-2xl font-black mt-1">${labels[active]}</h3>`;box.append(h);if(!rows.length){box.append(Object.assign(document.createElement('p'),{className:'mt-5 text-slate-500',textContent:'Chưa có dữ liệu.'}));return;}const list=document.createElement('div');list.className='mt-5 divide-y divide-slate-200';rows.forEach((r,i)=>{const row=document.createElement('div');row.className='flex items-center justify-between gap-4 py-4';const left=document.createElement('div');left.className='flex items-center gap-3';const rank=document.createElement('span');rank.className='w-9 h-9 rounded-full bg-slate-100 flex items-center justify-center font-black';rank.textContent=String(i+1);const name=document.createElement('span');name.className='font-bold';name.textContent=r.name;left.append(rank,name);const value=document.createElement('b');value.textContent=format(active,r.value);row.append(left,value);list.append(row);});box.append(list);}
 document.addEventListener('DOMContentLoaded',()=>{document.querySelectorAll('.lb-tab').forEach(b=>b.addEventListener('click',()=>{active=b.dataset.lb||'study';document.querySelectorAll('.lb-tab').forEach(x=>x.classList.toggle('active',x===b));render();}));});
 window.openUnifiedLeaderboard=()=>{switchSection('sec-leaderboard');load();};
 window.addEventListener('firebase:user-ready',()=>{if(document.getElementById('sec-leaderboard'))load();});
})();
