(function(){
 'use strict';
 const $=id=>document.getElementById(id),uid=()=>window.auth?.currentUser?.uid;
 let rooms=[],posts=[],history=[],loading=false,loadedUid='',lastLoaded=0,mode='overview';
 const localKey=name=>'htvvm.'+name+'.'+(uid()||'guest');
 const read=(name,fallback)=>HL.storage.get(localKey(name),fallback);
 const write=(name,value)=>HL.storage.set(localKey(name),value);
 const fold=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/đ/g,'d').toLowerCase();
 function button(text,fn){const el=document.createElement('button');el.type='button';el.className='hl-button';el.textContent=text;el.addEventListener('click',fn);return el;}
 function card(title,body){const el=document.createElement('article');el.className='hl-card';const h=document.createElement('h3');h.textContent=title;el.append(h);if(body){const p=document.createElement('p');p.textContent=body;el.append(p);}return el;}
 function storeItem(item){const saved=read('bookmarks',{}),id=item.type+':'+item.id;if(saved[id])delete saved[id];else saved[id]=item;write('bookmarks',saved);window.toast?.(saved[id]?'Đã lưu trên thiết bị này.':'Đã bỏ lưu.');}
 function openItem(item){if(item.type==='exam')prepareJoin(item.id);else if(item.type==='document'){const url=HL.safeURL(item.url);if(url)window.open(url,'_blank','noopener,noreferrer');}else if(item.type==='community')openCommunity();else switchSection(item.id);}
 function listItems(items,target){for(const item of items){const el=card(item.title,item.subtitle||'');el.append(button('Mở',()=>openItem(item)),button('Lưu / bỏ lưu',()=>storeItem(item)));target.append(el);}}
 async function load(force=false){
  if(!uid()||loading)return;const user=uid();if(!force&&loadedUid===user&&Date.now()-lastLoaded<60000)return;
  loading=true;
  try{const results=await Promise.all([HL.roomSnapshot(),db.ref(`users/${user}/examHistory`).once('value'),db.ref('community/posts').limitToLast(100).once('value')]);if(uid()!==user)return;
   rooms=Object.entries(results[0].val()||{}).filter(([,r])=>r.config).map(([id,r])=>({...r,id}));history=Object.values(results[1].val()||{}).sort((a,b)=>(b.date||0)-(a.date||0));posts=Object.entries(results[2].val()||{}).map(([id,p])=>({...p,id}));loadedUid=user;lastLoaded=Date.now();
  }catch(error){console.warn('Learning data',error);window.toast?.('Chưa tải đủ dữ liệu học tập. Bạn có thể thử tải lại.');}finally{loading=false;}
 }
 function items(){const docs=typeof docsData!=='undefined'?docsData:[];return [...rooms.map(r=>({id:r.id,type:'exam',title:r.title||'Đề thi',subtitle:`Đề thi · ${r.config.timeLimit} phút`})),...docs.map((d,i)=>({id:HL.safeURL(d.pdf_url||d.link||d.url)||String(i),type:'document',title:d.title||d.Title||d.Tên||'Tài liệu',url:HL.safeURL(d.pdf_url||d.link||d.url),subtitle:d.chapter||d['Môn']||'Tài liệu'})),...posts.map(p=>({id:p.id,type:'community',title:p.title||'Bài viết',subtitle:p.subject||'Cộng đồng'})),...['study','toolkit','chemmaker','stats','arena'].map((id,i)=>({id:'sec-'+id,type:'tool',title:['Học tập','Toolkit','Chemmaker','Thống kê','Đấu trường'][i]}))];}
 function metric(value,label){return card(String(value),label);}
 function overview(box){
  const correct=history.reduce((n,r)=>n+(Number(r.correct)||0),0),total=history.reduce((n,r)=>n+(Number(r.correct)||0)+(Number(r.wrong)||0)+(Number(r.blank)||0),0);
  const metrics=document.createElement('div');metrics.className='hl-grid';metrics.append(metric(history.length,'Số bài đã làm'),metric(history.length?(history.reduce((n,r)=>n+(Number(r.score)||0),0)/history.length).toFixed(2):'—','Điểm trung bình'),metric(total?Math.round(correct/total*100)+'%':'—','Độ chính xác của bài có dữ liệu chi tiết'));box.append(metrics);
  const recent=card('Tiếp tục học','Bài đang làm được lưu riêng cho tài khoản trên thiết bị này.');let drafts=0;
  for(let i=0;i<localStorage.length;i++){const key=localStorage.key(i);if(!key?.startsWith('htvvm.examDraft.')||!key.endsWith('.'+uid()))continue;const d=HL.storage.get(key);if(d?.uid===uid()&&d.status!=='submitted'){drafts++;recent.append(button(d.room?.title||'Tiếp tục đề',async()=>{await prepareJoin(d.roomId);$('studentName').value=d.name;await startExam();}));}}
  if(!drafts)recent.append(button('Chọn đề luyện tập',()=>loadExamList()));box.append(recent);
  const suggestions=card('Đề xuất luyện tập','Ưu tiên đề từng làm có điểm thấp, sau đó đến đề chưa làm. Chỉ gợi ý chuyên đề khi đề có metadata.');
  const average=new Map();for(const r of history){const v=average.get(r.roomId)||[];v.push(+r.score||0);average.set(r.roomId,v);}
  const rank=r=>average.has(r.id)?average.get(r.id).reduce((a,b)=>a+b,0)/average.get(r.id).length:7;
  listItems([...rooms].filter(r=>r.status!=='closed').sort((a,b)=>rank(a)-rank(b)).slice(0,4).map(r=>({id:r.id,type:'exam',title:r.title,subtitle:r.config.topic||'Chưa có chuyên đề'})),suggestions);box.append(suggestions);
  const recentResults=card('Kết quả gần đây');for(const r of history.slice(0,8)){const p=document.createElement('p');p.textContent=`${r.title||'Đề thi'} — ${r.score}/10`;recentResults.append(p);}if(!history.length)recentResults.append(document.createTextNode('Chưa có kết quả.'));recentResults.append(button('Xuất kết quả CSV',()=>exportCSV(history)));box.append(recentResults);
 }
 function exportCSV(rows){const fields=['title','name','score','timeSpent','correct','wrong','blank','date'];const quote=v=>'"'+String(v??'').replace(/^[=+@-]/,"'$&").replace(/"/g,'""')+'"';const csv='\ufeff'+[fields.join(','),...rows.map(r=>fields.map(k=>quote(r[k])).join(','))].join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='HTVVM-ket-qua.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 function mistakes(box){const all=Object.values(read('mistakes',{})),topics=[...new Set(all.map(x=>x.topic))];const header=card('Sổ tay câu sai','Lưu trên thiết bị này. Với đề PDF, mở tài liệu gốc để xem nội dung câu hỏi; hệ thống chỉ có phiếu đáp án.');const select=document.createElement('select');select.setAttribute('aria-label','Lọc chuyên đề');for(const t of ['Tất cả',...topics]){const option=document.createElement('option');option.textContent=t;select.append(option);}const list=document.createElement('div');header.append(select,button('Luyện tất cả câu sai',()=>practice(all,list)));box.append(header,list);
  function render(){list.replaceChildren();const rows=all.filter(x=>select.value==='Tất cả'||x.topic===select.value);for(const item of rows){const c=card(item.title+' · '+item.question,`${item.topic} · Sai ${item.count} lần · Bạn trả lời: ${item.answer||'Bỏ trống'} · Đáp án: ${item.expected}`);c.append(button('Luyện câu này',()=>practice([item],list)),button('Mở đề gốc',()=>prepareJoin(item.roomId)));list.append(c);}if(!rows.length)list.textContent='Chưa có câu sai trong chuyên đề này.';}
  select.addEventListener('change',render);render();
 }
 function practice(rows,box){box.replaceChildren();if(!rows.length){box.textContent='Chưa có câu sai để luyện.';return;}for(const item of rows){const c=card(item.title+' · '+item.question,'Xem câu hỏi trong tài liệu đề rồi nhập đáp án.');const input=document.createElement('input');input.setAttribute('aria-label','Đáp án '+item.question);const feedback=document.createElement('p');feedback.setAttribute('aria-live','polite');c.append(input,button('Kiểm tra',()=>{feedback.textContent=HL.normalize(input.value)===HL.normalize(item.expected)?'Chính xác.':'Chưa đúng. Đáp án: '+item.expected;}),button('Mở đề gốc',()=>{const url=HL.safeURL(item.pdf);if(url)window.open(url,'_blank','noopener,noreferrer');else window.toast?.('Đề chưa có tài liệu đính kèm.');}),feedback);box.append(c);}}
 function plan(box){const saved=read('studyPlan',{daily:60,weekly:300,exams:3,subject:'',topic:''});const c=card('Kế hoạch học tập','Mục tiêu lưu trên thiết bị này. Tiến độ lấy từ giờ học đã xác nhận và lịch sử thi.');const form=document.createElement('form');for(const [key,label]of Object.entries({daily:'Phút mỗi ngày',weekly:'Phút mỗi tuần',exams:'Số đề mỗi tuần',subject:'Môn học',topic:'Chuyên đề'})){const l=document.createElement('label');l.textContent=label;const input=document.createElement('input');input.name=key;input.value=saved[key];input.type=['subject','topic'].includes(key)?'text':'number';input.required=!['subject','topic'].includes(key);input.min='1';input.max='10080';input.maxLength=160;l.append(input);form.append(l);}const submit=button('Lưu kế hoạch',()=>{});submit.type='submit';form.append(submit);form.addEventListener('submit',e=>{e.preventDefault();const data=Object.fromEntries(new FormData(form));write('studyPlan',data);window.setDailyGoal?.(+data.daily);window.toast?.('Đã lưu kế hoạch.');});c.append(form);box.append(c);}
 function teacher(box){const mine=rooms.filter(r=>r.creatorUid===uid()),results=mine.flatMap(r=>Object.values(r.results||{}).map(x=>({...x,title:r.title}))),people=new Set(results.map(r=>r.uid||r.name));const m=document.createElement('div');m.className='hl-grid';m.append(metric(mine.length,'Đề của tôi'),metric(results.length,'Lượt làm'),metric(people.size,'Học sinh (dữ liệu cũ tính theo tên)'));box.append(m);const actions=card('Khu vực giáo viên');actions.append(button('Tạo đề',()=>openTeacherConfig()),button('Ngân hàng câu hỏi',()=>arenaOpenQuestionStudio()),button('Xuất danh sách điểm',()=>exportCSV(results)));box.append(actions);
  for(const r of mine){const c=card(r.title,`${r.status||'open'} · ${Object.keys(r.results||{}).length} lượt làm`);c.append(button('Bảng điểm',()=>viewLeaderboard(r.id)),button(r.status==='closed'?'Mở đề':'Đóng đề',async()=>{try{await db.ref('rooms/'+r.id+'/status').set(r.status==='closed'?'open':'closed');await load(true);render();}catch{window.toast?.('Không thể cập nhật đề.');}}),button('Nhân bản',async()=>{try{const ref=db.ref('rooms').push();await ref.set({title:r.title+' (bản sao)',creatorUid:uid(),creatorName:r.creatorName||'',createdAt:firebase.database.ServerValue.TIMESTAMP,status:'closed',config:r.config,answers:r.answers||{}});await load(true);render();}catch{window.toast?.('Không thể nhân bản đề.');}}));box.append(c);}
 }
 function notifications(box){const c=card('Thông báo học tập','Thông báo được tổng hợp từ kết quả và lịch của bạn.');for(const r of history.slice(0,5)){const p=document.createElement('p');p.textContent=`Kết quả: ${r.title||'Đề thi'} — ${r.score}/10`;c.append(p);}const events=typeof calendarEvents!=='undefined'?Object.values(calendarEvents):[];for(const e of events.filter(e=>e.date>=HL.dayKey()).slice(0,5)){const p=document.createElement('p');p.textContent=`${e.date} · ${e.title}`;c.append(p);}if(!history.length&&!events.length)c.append(document.createTextNode('Chưa có thông báo.'));box.append(c);}
 function render(){const box=$('hl-learning-body');if(!box)return;box.replaceChildren();({overview,mistakes,plan,teacher,notifications,saved:target=>{const list=Object.values(read('bookmarks',{}));if(!list.length)target.textContent='Chưa lưu đề hoặc tài liệu.';else listItems(list,target);}}[mode]||overview)(box);}
 async function open(next='overview'){mode=next;switchSection('sec-learning');$('hl-learning-body').textContent='Đang tải dữ liệu…';await load();render();}
 async function search(){const dialog=$('hl-search');dialog.showModal();$('hl-query').focus();await load();searchResults();}
 function searchResults(){const query=fold($('hl-query').value).trim();const target=$('hl-search-results');target.replaceChildren();const found=items().filter(item=>!query||fold(item.title+' '+item.subtitle).includes(query)).slice(0,40);if(!found.length)target.textContent='Không tìm thấy kết quả.';for(const item of found){const c=card(item.title,item.subtitle);c.append(button('Mở',()=>{ $('hl-search').close();openItem(item);}),button('Lưu / bỏ lưu',()=>storeItem(item)));target.append(c);}}
 window.HLLearning={open,bookmark:storeItem,recordMistakes(attempt,result){const saved=read('mistakes',{});for(const d of result.details.filter(d=>!d.correct&&d.expected)){const key=attempt.roomId+':'+d.id,old=saved[key];if(old?.attemptId===attempt.id)continue;saved[key]={roomId:attempt.roomId,title:attempt.room.title,question:d.id,answer:d.answer,expected:d.expected,topic:attempt.room.config.topic||'Chưa phân loại',pdf:attempt.room.config.pdfUrl||'',count:(old?.count||0)+1,lastAt:Date.now(),attemptId:attempt.id};}write('mistakes',saved);}};
 document.addEventListener('DOMContentLoaded',()=>{
  const section=document.createElement('section');section.id='sec-learning';section.className='app-section hidden';section.innerHTML='<header class="hl-page-heading"><p>KHÔNG GIAN HỌC TẬP</p><h1>Học có mục tiêu, tiến bộ mỗi ngày.</h1><p>Tiếp tục bài đang làm, luyện lại câu sai và theo dõi kết quả của bạn.</p></header><div id="hl-tabs" class="hl-tabs"></div><div id="hl-learning-body"></div>';document.body.append(section);
  for(const [key,label]of Object.entries({overview:'Tổng quan',mistakes:'Sổ tay câu sai',plan:'Kế hoạch học tập',saved:'Đã lưu',notifications:'Thông báo',teacher:'Giáo viên'}))$('hl-tabs').append(button(label,()=>open(key)));
  const nav=$('nav-home')?.parentElement;if(nav){const b=button('Sổ tay & Kế hoạch',()=>open());b.id='nav-learning';b.classList.add('nav-btn');nav.append(b);for(const [id,label,action] of [['arena','Đấu trường',()=>openChemArena()],['teacher','Khu vực giáo viên',()=>open('teacher')],['chemmaker','Chemmaker',()=>openChemMaker()],['toolkit','Toolkit',()=>openToolkit()],['stats','Thống kê',()=>openStats()]]){if($('nav-'+id))continue;const item=button(label,action);item.id='nav-'+id;item.classList.add('nav-btn');nav.append(item);}}
  const dialog=document.createElement('dialog');dialog.id='hl-search';dialog.className='hl-dialog';dialog.innerHTML='<div class="hl-dialog-head"><h2>Tìm kiếm toàn website</h2><button id="hl-search-close" aria-label="Đóng tìm kiếm">✕</button></div><input id="hl-query" placeholder="Tìm đề, tài liệu, công cụ, cộng đồng…" aria-label="Từ khóa tìm kiếm"><div id="hl-search-results"></div>';document.body.append(dialog);$('hl-search-close').addEventListener('click',()=>dialog.close());let timeout;$('hl-query').addEventListener('input',()=>{clearTimeout(timeout);timeout=setTimeout(searchResults,180);});
  const bar=document.createElement('div');bar.id='hl-topbar';bar.append(button('Tìm kiếm… Ctrl K',search),button('Kế hoạch của tôi',()=>open('plan')),button('Thông báo',()=>open('notifications')));$('main-nav')?.prepend(bar);
  const intro=card('Ôn tập thông minh. Luyện đề hiệu quả.','Bắt đầu từ bài còn dang dở hoặc dành ít phút cho những câu cần luyện lại.');intro.classList.add('hl-hero');intro.append(button('Tiếp tục học',()=>open()),button('Sổ tay câu sai',()=>open('mistakes')));$('sec-dashboard')?.prepend(intro);
  if('serviceWorker' in navigator)navigator.serviceWorker.register('/sw.js').catch(error=>console.warn('Offline shell unavailable',error));
 });
 document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();if(uid())search();}});
 document.addEventListener('hl:exam-result',()=>{lastLoaded=0;});
 window.addEventListener('firebase:user-ready',()=>{if(loadedUid!==uid()){rooms=[];history=[];posts=[];loadedUid='';lastLoaded=0;}});
})();
