(function(){'use strict';
 const state={catalog:[],owned:new Set(),wallet:{balance:0},accent:localStorage.getItem('htvvm_accent')||'#2563eb',theme:localStorage.getItem('htvvm_theme_id')||'classic'};
 const $=id=>document.getElementById(id);
 function hexToRgb(hex){const m=String(hex).replace('#','').match(/^([0-9a-f]{6})$/i);if(!m)return null;const n=parseInt(m[1],16);return {r:n>>16&255,g:n>>8&255,b:n&255};}
 function mix(hex,target,amount){const c=hexToRgb(hex);if(!c)return hex;const t=target==='white'?255:0;const a=Math.min(1,Math.max(0,amount));return '#'+[c.r,c.g,c.b].map(v=>Math.round(v+(t-v)*a).toString(16).padStart(2,'0')).join('');}
 function applyAccent(hex){if(!/^#[0-9a-f]{6}$/i.test(hex))return;state.accent=hex;const root=document.documentElement;root.style.setProperty('--accent',hex);root.style.setProperty('--accent-soft',mix(hex,'white',.9));root.style.setProperty('--accent-strong',mix(hex,'black',.18));root.style.setProperty('--accent-text',mix(hex,'black',.48));root.style.setProperty('--accent-border',mix(hex,'white',.55));const rgb=hexToRgb(hex);if(rgb)root.style.setProperty('--accent-glow',`rgba(${rgb.r},${rgb.g},${rgb.b},.22)`);document.body.classList.add('accent-enabled');localStorage.setItem('htvvm_accent',hex);}
 function previewStyle(theme){const map={classic:['#2563eb','#22d3ee'],anime:['#ec4899','#8b5cf6'],football:['#16a34a','#0f766e'],volleyball:['#f97316','#facc15'],magic:['#8b5cf6','#06b6d4'],ice:['#0ea5e9','#e0f2fe'],fire:['#ef4444','#f97316'],space:['#312e81','#0ea5e9'],cyber:['#06b6d4','#2563eb'],chemistry:['#14b8a6','#22c55e'],aurora:['#22c55e','#06b6d4'],fantasy:['#a855f7','#ec4899'],'minimal-dark':['#475569','#94a3b8']};return map[theme.preview]||map.classic;}
 function applyTheme(id){const theme=state.catalog.find(x=>x.id===id)||state.catalog.find(x=>x.id==='classic');if(!theme)return false;if(theme.premium&&!state.owned.has(theme.id))return false;state.theme=theme.id;localStorage.setItem('htvvm_theme_id',theme.id);document.body.dataset.theme=theme.slug;applyAccent(theme.accent||state.accent);document.documentElement.classList.toggle('theme-dark',theme.id==='minimal-dark');return true;}
 async function api(method,body){const user=window.auth?.currentUser;if(!user)throw new Error('AUTH');const token=await user.getIdToken();const r=await fetch('/api/themes',{method,headers:{'Content-Type':'application/json',Authorization:'Bearer '+token},body:body?JSON.stringify(body):undefined,cache:'no-store'});let d={};try{d=await r.json()}catch{}if(!r.ok)throw Object.assign(new Error(d.error||'Theme API error'),{status:r.status,data:d});return d;}
 function render(){const host=$('sec-theme-store');if(!host)return;host.innerHTML='';const shell=document.createElement('div');shell.className='theme-shell';const head=document.createElement('div');head.className='hl-card p-6';head.innerHTML='<p class="text-xs font-black tracking-[.2em] text-cyan-600 uppercase">THEME SYSTEM</p><h1 class="text-3xl font-black mt-1">Theme Store</h1><p class="text-sm text-slate-500 mt-2">Accent miễn phí. Theme premium có giá 2.500 token và ownership được kiểm tra từ máy chủ.</p>';const wallet=document.createElement('div');wallet.className='mt-4 flex flex-wrap items-center gap-2';wallet.innerHTML=`<span class="hl-theme-nav">🪙 Số dư: ${state.wallet.balance.toLocaleString('vi-VN')} token</span><button id="theme-support" class="px-3 py-2 rounded-xl bg-cyan-50 text-cyan-700 font-black">Nạp token qua Zalo</button>`;head.append(wallet);shell.append(head);
  const accent= document.createElement('section');accent.className='hl-card p-6';accent.innerHTML='<h2 class="font-black text-xl mb-1">FREE · Accent Color</h2><p class="text-sm text-slate-500 mb-4">Chỉ đổi accent; giao diện Legacy vẫn giữ nguyên.</p>';const pal=document.createElement('div');pal.className='accent-palette';for(const c of ['#2563eb','#7c3aed','#dc2626','#ea580c','#eab308','#16a34a','#ec4899','#06b6d4','#14b8a6']){const b=document.createElement('button');b.className='accent-chip';b.style.background=c;b.title=c;b.onclick=()=>applyAccent(c);pal.append(b);}accent.append(pal);const custom=document.createElement('div');custom.className='accent-custom mt-4';custom.innerHTML='<span class="text-sm font-bold">Màu tùy chỉnh</span>';const input=document.createElement('input');input.type='color';input.value=state.accent;input.oninput=e=>applyAccent(e.target.value);custom.append(input);accent.append(custom);shell.append(accent);
  const grid=document.createElement('div');grid.className='theme-grid';for(const theme of state.catalog){const card=document.createElement('article');card.className='theme-card';const [a,b]=previewStyle(theme);card.innerHTML=`<div class="theme-preview" style="--preview-a:${a};--preview-b:${b}"></div><div class="theme-meta"><div><h3 class="font-black text-lg">${theme.name}</h3><p class="text-xs text-slate-500 mt-1">${theme.description}</p></div><span class="theme-price">${theme.premium?'2.500 token':'FREE'}</span></div>`;const actions=document.createElement('div');actions.className='theme-actions';if(state.theme===theme.id&&(!theme.premium||state.owned.has(theme.id))){const active=document.createElement('button');active.className='theme-apply';active.textContent='Đang dùng';active.disabled=true;actions.append(active);}else if(theme.premium&&!state.owned.has(theme.id)){const buy=document.createElement('button');buy.className='theme-buy';buy.textContent=state.wallet.balance>=2500?'Mua 2.500 token':'Cần thêm token';buy.disabled=state.wallet.balance<2500;buy.onclick=async()=>{try{const data=await api('POST',{themeId:theme.id});state.wallet=data.wallet;state.owned=new Set(data.owned||[...state.owned,theme.id]);render();window.toast?.(data.alreadyOwned?'Theme đã sở hữu.':'Mua theme thành công.');}catch(e){window.toast?.(e.data?.error||'Không thể mua theme.');}};actions.append(buy);}else{const use=document.createElement('button');use.className='theme-apply';use.textContent='Dùng theme';use.onclick=()=>{applyTheme(theme.id);render();};actions.append(use);}card.append(actions);grid.append(card);}shell.append(grid);host.append(shell);$('theme-support')?.addEventListener('click',()=>showSupport());}
 async function showSupport(){try{const d=await api('GET');const s=d.support;if(s?.url){window.open(s.url,'_blank','noopener,noreferrer');}else window.toast?.('Admin chưa cấu hình kênh Zalo hỗ trợ trong Vercel Environment Variables.');}catch{window.toast?.('Chưa thể tải thông tin hỗ trợ.');}}
 async function load(){try{const d=await api('GET');state.catalog=d.themes||[];state.owned=new Set(d.owned||[]);state.wallet=d.wallet||{balance:0};if(!applyTheme(state.theme))applyTheme('classic');applyAccent(state.accent);render();}catch(e){console.warn('theme system',e);state.catalog=[{id:'classic',name:'Classic / Tailwind Legacy',description:'Giao diện hiện tại',premium:false,accent:'#2563eb',preview:'classic'}];applyTheme('classic');render();}}
 window.HLTheme={load,render,applyAccent,applyTheme,get state(){return state;},open(){switchSection('sec-theme-store');load();}};
 document.addEventListener('DOMContentLoaded',()=>{applyAccent(state.accent);const nav=$('#main-nav .nav-btn')?.parentElement;if(nav&&!$('#nav-theme-store')){const b=document.createElement('button');b.id='nav-theme-store';b.className='nav-btn text-slate-600 px-4 py-2.5 rounded-xl font-bold text-sm whitespace-nowrap transition-all hover:bg-white';b.textContent='🎨 Theme';b.onclick=()=>window.HLTheme.open();nav.append(b);}load();});
 window.addEventListener('firebase:user-ready',()=>load());
})();
