// Isolated QA fixtures only. This file is never loaded by the website.
const fs=require('fs'),path=require('path'),http=require('http');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const root=path.resolve(__dirname,'..'),report={errors:[],widths:[],checks:[]};
const {beginAttempt,advanceAttempt}=require('../lib/exam-core');
const examRoom={title:'Đề kiểm thử',creatorUid:'test',creatorName:'Giáo viên kiểm thử',status:'open',config:{abcd:1,tf:1,short:1,timeLimit:15,pdfUrl:''},answers:{abcd_1:'B',tf_1_0:'D',tf_1_1:'S',tf_1_2:'D',tf_1_3:'S',short_1:'1.5'}};
const attempts={};let rejectSubmit=false;
const server=http.createServer((req,res)=>{const url=new URL(req.url,'http://localhost');if(url.pathname==='/api/time'){res.setHeader('Content-Type','application/json');res.end(JSON.stringify({serverTime:Date.now()}));return;}let file=path.resolve(root,'.'+decodeURIComponent(url.pathname==='/'?'/index.html':url.pathname));if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return;}if(!fs.existsSync(file)){res.writeHead(404).end();return;}res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.css':'text/css','.png':'image/png'})[path.extname(file)]||'text/plain');res.end(fs.readFileSync(file));});
(async()=>{await new Promise(r=>server.listen(43827,'127.0.0.1',r));const browser=await chromium.launch({headless:true,executablePath:process.env.BROWSER_EXECUTABLE||undefined});const page=await browser.newPage({serviceWorkers:'block',viewport:{width:1440,height:1000}});page.on('pageerror',e=>{report.errors.push(e.message);console.log('PAGE ERROR',e.message)});page.on('console',m=>{if(m.type()==='warning')console.log('BROWSER WARNING',m.text())});page.on('dialog',async d=>{console.log('DIALOG',d.message());await d.dismiss()});
await page.route('**/www.gstatic.com/firebasejs/**',route=>route.fulfill({body:'',contentType:'application/javascript'}));
await page.route('**/js/vendor/firebase-*.js',route=>route.fulfill({body:'',contentType:'application/javascript'}));
await page.route('**/*',route=>{const url=new URL(route.request().url());if(url.hostname==='127.0.0.1'||url.hostname==='docs.google.com')return route.fallback();return route.fulfill({body:'',contentType:'text/javascript'});});
await page.route('**/docs.google.com/**',route=>route.fulfill({body:'title,chapter,pdf_url\nDe Hoa,Hoa hoc,https://drive.google.com/file/d/example/view',contentType:'text/csv'}));
await page.route('**/api/study-time',route=>route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'Test unavailable backend'})}));
await page.route('**/api/gemini',route=>route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'Test AI unavailable'})}));
await page.route('**/api/rooms**',route=>route.fulfill({contentType:'application/json',body:JSON.stringify({data:new URL(route.request().url()).searchParams.has('id')?examRoom:{ABC123:examRoom}})}));
await page.route('**/api/leaderboards',route=>route.fulfill({contentType:'application/json',body:JSON.stringify({study:[],streak:[]})}));
await page.route('**/api/exam',async route=>{const body=route.request().postDataJSON(),id=body.attemptId,now=Date.now();if(rejectSubmit&&body.action==='submit')return route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'Test rejected write'})});if(body.action==='start')attempts[id]??=beginAttempt(examRoom,{uid:'test',name:body.name},id,now);else if(body.action!=='resume')attempts[id]=advanceAttempt(attempts[id],body.action,body,now);const a=attempts[id],entry=a.status==='submitted'?{score:a.result.score,timeSpent:a.timeSpent,attemptId:id,title:a.title}:null;return route.fulfill({contentType:'application/json',body:JSON.stringify({serverTime:now,id,startAt:a.startAt,duration:a.duration,status:a.status,revision:a.revision,answers:a.answers,config:a.config,title:a.title,entry,result:a.result||null,allowReview:true,usedCheckpoint:!!a.usedCheckpoint})});});
await page.addInitScript(()=>{
 const data={users:{test:{name:'Học viên kiểm thử',totalStudySeconds:0}},rooms:{ABC123:{title:'Đề kiểm thử',creatorUid:'test',creatorName:'Giáo viên kiểm thử',status:'open',config:{abcd:1,tf:1,short:1,timeLimit:15,pdfUrl:''},answers:{abcd_1:'B',tf_1_0:'D',tf_1_1:'S',tf_1_2:'D',tf_1_3:'S',short_1:'1.5'}}}};
 const watchers=new Map();let counter=0;const get=p=>p.split('/').filter(Boolean).reduce((v,k)=>v?.[k],data);function put(p,v){const parts=p.split('/').filter(Boolean);let node=data;for(const k of parts.slice(0,-1))node=node[k]??={};if(v===null)delete node[parts.at(-1)];else node[parts.at(-1)]=v;}
 const snap=(v,key)=>({val:()=>v??null,exists:()=>v!=null,key,forEach(fn){Object.entries(v||{}).forEach(([k,x])=>fn(snap(x,k)));}});
 function ref(p=''){return {key:p.split('/').at(-1),child:k=>ref(p+'/'+k),orderByChild(){return this;},limitToLast(){return this;},once:async()=>snap(get(p)),on(event,fn){watchers.set(p,fn);queueMicrotask(()=>fn(snap(get(p))));},off(){watchers.delete(p);},async set(v){put(p,v);},async update(v){for(const [k,x]of Object.entries(v))put(p+'/'+k,x);},async remove(){put(p,null);},async transaction(fn){const v=fn(get(p)??null);if(v!==undefined)put(p,v);return {committed:v!==undefined,snapshot:snap(v)};},push(v){const r=ref(p+'/test'+(++counter));if(v)return r.set(v);return r;},onDisconnect(){return {remove:async()=>{},cancel:async()=>{},set:async()=>{}};}};}
 const user={uid:'test',displayName:'Học viên kiểm thử',email:'test@example.invalid',photoURL:'',getIdToken:async()=>'test-token'},callbacks=[];
 const auth={currentUser:user,onAuthStateChanged(fn){callbacks.push(fn);queueMicrotask(()=>fn(this.currentUser));return()=>{};},async signInWithPopup(){this.currentUser=user;callbacks.forEach(f=>f(user));},async signOut(){this.currentUser=null;callbacks.forEach(f=>f(null));}};
 const factory=()=>auth;factory.GoogleAuthProvider=function(){};const database=()=>({ref});database.ServerValue={TIMESTAMP:Date.now()};window.firebase={apps:[{}],auth:factory,database,initializeApp(){}};window.__testData=data;
});
await page.goto('http://127.0.0.1:43827/',{waitUntil:'domcontentloaded',timeout:60000});await page.waitForTimeout(700);
for(const width of [1440,1280,1024,768,480,390,360]){await page.setViewportSize({width,height:950});await page.evaluate(()=>switchSection('sec-dashboard'));await page.waitForTimeout(150);report.widths.push({width,...await page.evaluate(()=>({scroll:document.documentElement.scrollWidth,client:document.documentElement.clientWidth,active:document.querySelector('.app-section.active')?.id}))});if([1440,390].includes(width))await page.screenshot({path:`docs/preview-${width}.png`,fullPage:true});}
await page.evaluate(()=>HLLearning.open('overview'));await page.waitForTimeout(200);report.checks.push({learning:await page.locator('#hl-learning-body').innerText()});
await page.evaluate(()=>openCalendar());await page.waitForTimeout(200);report.checks.push({calendarDays:await page.locator('#calendar-days button').count()});await page.evaluate(()=>closeCalendar());
await page.evaluate(async()=>{await prepareJoin('ABC123');document.getElementById('studentName').value='Test';await startExam();saveAns('abcd_1','B');saveAns('short_1','1,5');});
report.checks.push({examActive:await page.locator('#sec-taking-exam').getAttribute('class')});
await page.reload({waitUntil:'domcontentloaded'});await page.waitForTimeout(300);await page.evaluate(async()=>{await prepareJoin('ABC123');document.getElementById('studentName').value='Test';await startExam();});report.checks.push({restoredShort:await page.locator('#input-short_1').inputValue(),stateShort:await page.evaluate(()=>answers.short_1)});
rejectSubmit=true;await page.evaluate(()=>submitExam());report.checks.push({failedSubmitRetainsDraft:await page.evaluate(()=>HL.storage.get(`htvvm.examDraft.ABC123.test`)?.status==='pending')});rejectSubmit=false;
await page.evaluate(()=>Promise.all([submitExam(),submitExam()]));report.checks.push({score:await page.locator('#score').innerText(),results:Object.values(attempts).filter(a=>a.status==='submitted').length});
await page.evaluate(()=>{document.getElementById('chem-editor').value='<img src=x onerror="window.__xss=true"><script>window.__xss=true</script><b>Safe</b>';updateChemPreview();});report.checks.push({xss:await page.evaluate(()=>!!window.__xss),chem:await page.locator('#chem-pdf-content').innerHTML()});
await page.evaluate(()=>switchSection('sec-library'));await page.evaluate(()=>switchSection('sec-study'));await page.goBack();report.checks.push({back:await page.evaluate(()=>document.querySelector('.app-section.active')?.id)});
await page.evaluate(()=>HLLearning.open('plan'));await page.locator('input[name=daily]').fill('45');await page.getByRole('button',{name:'Lưu kế hoạch',exact:true}).click();report.checks.push({planSaved:await page.evaluate(()=>HL.storage.get('htvvm.studyPlan.test')?.daily)});
await page.evaluate(()=>switchSection('sec-dashboard'));await page.keyboard.press('Control+k');report.checks.push({searchDialog:await page.locator('#hl-search').evaluate(el=>el.open)});await page.keyboard.press('Escape');
report.sectionWidths=[];
for(const width of [1440,1280,1024,768,480,390,360]){await page.setViewportSize({width,height:950});for(const id of ['sec-library','sec-exam-list','sec-teacher-config','sec-teacher-key','sec-chemmaker','sec-toolkit','sec-study','sec-community','sec-arena','sec-arena-creator','sec-learning']){await page.evaluate(id=>switchSection(id),id);const measured=await page.evaluate(()=>({scroll:document.documentElement.scrollWidth,client:document.documentElement.clientWidth}));report.sectionWidths.push({width,id,...measured});}}
await page.evaluate(()=>switchSection('sec-library'));const preview=page.getByRole('button',{name:'Xem trước',exact:true}).first();if(await preview.count()){await preview.click();report.checks.push({documentPreview:await page.locator('#hl-document-preview').evaluate(el=>el.open)});await page.locator('#hl-document-preview').getByRole('button',{name:'Đóng',exact:true}).click();}
await page.evaluate(()=>auth.signOut());report.checks.push({logoutHidesSections:await page.locator('.app-section.active').count()===0});
fs.writeFileSync('docs/browser-test.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));await browser.close();server.close();
const assert=require('node:assert/strict');assert.deepEqual(report.errors,[]);assert.ok(report.widths.every(w=>w.scroll===w.client));assert.ok(report.sectionWidths.every(w=>w.scroll===w.client),'Section overflows viewport');assert.ok(report.checks.some(c=>c.results===1));assert.ok(report.checks.some(c=>c.restoredShort==='1,5'&&c.stateShort==='1,5'));assert.ok(report.checks.some(c=>c.failedSubmitRetainsDraft));assert.ok(report.checks.some(c=>c.logoutHidesSections));
})().catch(e=>{console.error(e);server.close();process.exit(1)});

