const test=require('node:test'),assert=require('node:assert/strict');
const {applyStudy,dayKey}=require('../lib/study-core');const {grade,safeURL,esc,validateConfig}=require('../js/core');
const base=Date.parse('2026-09-15T00:00:00Z');
test('second active tab cannot create a second trusted session',()=>{let u=applyStudy({},'start','a',base,{clientInstanceId:'tab-a'});assert.ok(u);assert.equal(applyStudy(u,'start','b',base,{clientInstanceId:'tab-b'}),undefined);u=applyStudy(u,'heartbeat','a',base+15000,{clientInstanceId:'tab-a'});assert.equal(u.totalStudySeconds,15);});
test('same client start is idempotent and reuses the trusted session',()=>{let u=applyStudy({},'start','a',base,{clientInstanceId:'tab-a'});const v=applyStudy(u,'start','b',base+1000,{clientInstanceId:'tab-a'});assert.equal(v.__result.sessionId,'a');});
test('replayed heartbeat does not add time twice',()=>{let u=applyStudy({},'start','a',base,{clientInstanceId:'tab-a'});u=applyStudy(u,'heartbeat','a',base+15000);const before=u.totalStudySeconds;u=applyStudy(u,'heartbeat','a',base+15000);assert.equal(u.totalStudySeconds,before);});
test('offline backlog is rejected but later heartbeats can resume accounting',()=>{let u=applyStudy({},'start','a',base,{clientInstanceId:'tab-a'});u=applyStudy(u,'heartbeat','a',base+3600000);assert.equal(u.totalStudySeconds,0);u=applyStudy(u,'heartbeat','a',base+3615000);assert.equal(u.totalStudySeconds,15);});
test('Vietnam midnight splits accepted seconds between dates',()=>{const midnight=Date.parse('2026-09-15T17:00:00Z');let u=applyStudy({},'start','a',midnight-15000,{clientInstanceId:'tab-a'});u=applyStudy(u,'heartbeat','a',midnight+15000);assert.equal(u.dailyStudy['2026-09-15'],15);assert.equal(u.dailyStudy['2026-09-16'],15);assert.equal(u.totalStudySeconds,30);assert.equal(dayKey(midnight),'2026-09-16');});
test('five hour confirmation caps elapsed time and continue opens a new trusted window',()=>{let u=applyStudy({},'start','a',base,{clientInstanceId:'tab-a'});u.studySessions.a.lastHeartbeatAt=base+FIVE_HOURS_FIX()-15000;u=applyStudy(u,'heartbeat','a',base+FIVE_HOURS_FIX()+15000);assert.equal(u.totalStudySeconds,15);assert.equal(applyStudy(u,'continue','a',base+FIVE_HOURS_FIX()+31000),undefined);const v=applyStudy(u,'continue','a',base+FIVE_HOURS_FIX()+20000);assert.ok(v.studySessions.a.confirmAt>u.studySessions.a.confirmAt);});
test('stop is terminal and preserves unrelated legacy fields',()=>{let u=applyStudy({name:'Existing',totalStudySeconds:20,dailyStudy:{'2020-01-01':20}},'start','a',base,{clientInstanceId:'tab-a'});u=applyStudy(u,'stop','a',base+1000);assert.equal(u.name,'Existing');assert.equal(u.totalStudySeconds,21);assert.equal(applyStudy(u,'heartbeat','a',base+15000),undefined);});
test('grade follows existing weighted ABCD TF and short rubric',()=>{const c={abcd:1,tf:1,short:1,timeLimit:15},key={abcd_1:'B',tf_1_0:'D',tf_1_1:'S',tf_1_2:'D',tf_1_3:'S',short_1:'1.5'};assert.equal(grade(c,key,{...key,short_1:'1,5'}).score,10);const r=grade(c,key,{abcd_1:'A',tf_1_0:'D'});assert.equal(r.correct,1);assert.equal(r.wrong,1);assert.equal(r.blank,4);assert.equal(r.parts.tf,.1);});
test('blank answer never equals missing key',()=>{const r=grade({abcd:1,tf:0,short:0,timeLimit:10},{},{});assert.equal(r.score,0);assert.equal(r.blank,1);});
test('invalid configs reject NaN, negative, huge and empty papers',()=>{for(const c of [{abcd:0,tf:0,short:0,timeLimit:10},{abcd:1,tf:0,short:0,timeLimit:NaN},{abcd:201,tf:0,short:0,timeLimit:10}])assert.equal(validateConfig(c),false);});
test('URLs and attribute escaping reject active content',()=>{for(const url of ['javascript:alert(1)','data:text/html,test','//evil.test','https://user:pass@evil.test'])assert.equal(safeURL(url),'');assert.equal(safeURL('https://drive.google.com/file/d/abc/view'),'https://drive.google.com/file/d/abc/view');assert.equal(esc('"\' <>&'),'&quot;&#39; &lt;&gt;&amp;');});
function FIVE_HOURS_FIX(){return 18_000_000}
